import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "start layout",
  description: "Generated by create next app",
};

export default function Layout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <>
      <main>
        {children}
        {modal}
      </main>
    </>
  );
}
