import type { Metadata } from "next";
import Footer from "@/components/start/Footer";

export const metadata: Metadata = {
  title: "start layout",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <main>{children}</main>
      <Footer />
    </>
  );
}
